# Generated by Django 4.2.27 on 2026-01-30 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('rotation', models.FloatField(default=0)),
                ('scaleX', models.FloatField(default=1)),
                ('scaleY', models.FloatField(default=1)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceGripIndex', models.IntegerField()),
                ('targetGripIndex', models.IntegerField()),
                ('waypoints', models.JSONField()),
                ('sourceItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='api.canvasstate')),
                ('targetItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='api.canvasstate')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=10, unique=True)),
                ('parent', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('legend', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('object', models.CharField(max_length=100)),
                ('svg', models.FileField(blank=True, null=True, upload_to='components/')),
                ('png', models.ImageField(blank=True, null=True, upload_to='components/')),
                ('grips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='canvasstate',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.component'),
        ),
        migrations.AddField(
            model_name='canvasstate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
