# Generated by Django 4.2.27 on 2026-02-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
