# Generated by Django 4.2.27 on 2026-02-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_component_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='grips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='component',
            name='object',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
